name: Build ServiceStack.Text

on:
  push:
    paths:
      - 'ServiceStack.Text/**'
      - '.github/workflows/build-text.yml'

jobs:
  build-text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.100'
          
          
      - name: Build
        working-directory: ServiceStack.Text/build
        run: dotnet build ./build.proj
        
      - name: Env setup
        run: |
          echo "SERVICESTACK_LICENSE=${{ secrets.SERVICESTACK_LICENSE }}" >> $GITHUB_ENV
        
      - name: Text tests
        run: dotnet test --framework net8.0 ./ServiceStack.Text/tests/ServiceStack.Text.Tests/ServiceStack.Text.Tests.csproj  --logger 'trx;LogFileName=test-results.trx'

      - name: Text Tests Report
        uses: dorny/test-reporter@v1
        if: (success() || failure()) && steps.test_integration.outcome != 'skipped'
        with:
          name: Text Tests
          path: ./ServiceStack.Text/tests/ServiceStack.Text.Tests/TestResults/test-results.trx
          reporter: dotnet-trx
          only-summary: 'true'
          