name: Build Azure

on:
  push:
    paths:
      - 'ServiceStack.Azure/**'
      - '.github/workflows/build-azure.yml'

permissions:
  contents: read

jobs:
  build-azure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.100'
          

      - name: Build
        working-directory: ServiceStack.Azure/build
        run: dotnet build ./build.proj

      - name: Env setup
        run: |
          echo "SERVICESTACK_LICENSE=${{ secrets.SERVICESTACK_LICENSE }}" >> $GITHUB_ENV

# Azure tests need mocking.
#      - name: Azure Tests
#        run: dotnet test --framework net8.0 ./ServiceStack.Azure/tests/ServiceStack.Azure.Tests/ServiceStack.Azure.Tests.csproj  --logger 'trx;LogFileName=results.trx'
#
#      - name: Test Report
#        uses: dorny/test-reporter@v1
#        if: (success() || failure()) && steps.test_integration.outcome != 'skipped'
#        with:
#          name: Text Tests
#          path: ./ServiceStack.Azure/tests/ServiceStack.Azure.Tests/TestResults/results.trx
#          reporter: dotnet-trx
#          only-summary: 'true'
          