name: Build Core

on:
  push:
    paths:
      - 'ServiceStack.Core/**'
      - '.github/workflows/build-core.yml'

permissions:
  contents: read

jobs:
  build-servicestack-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.100'
          
          
      - name: Build
        working-directory: ServiceStack.Core/build
        run: dotnet build ./build.proj   
          